import { StarIcon, CalendarCheckIcon, ReceiptTextIcon, Cancel01Icon } from "@hugeicons/core-free-icons";

export const initialBookingsData = [
  {
    clientName: "Sara L.",
    clientPhone: "+357 99 123 456",
    clientInitials: "SL",
    isNew: true,
    bookingId: "#BK-0041",
    date: "Mon, 11 May",
    time: "09:00",
    staff: "Anna",
    status: "Upcoming",
    amount: "€90",
    paymentType: "Pay at venue"
  },
  {
    clientName: "Yiota M.",
    clientPhone: "+357 96 901 234",
    clientInitials: "YM",
    isNew: false,
    bookingId: "#BK-0040",
    date: "Wed, 13 May",
    time: "10:00",
    staff: "George",
    status: "Completed",
    amount: "€60",
    paymentType: "Prepaid"
  },
  {
    clientName: "Maria K.",
    clientPhone: "+357 96 567 444",
    clientInitials: "MK",
    isNew: true,
    bookingId: "#BK-0039",
    date: "Thu, 14 May",
    time: "11:30",
    staff: "Anna",
    status: "No-show - charged",
    amount: "€45",
    paymentType: "Pay at venue"
  },
  {
    clientName: "Christos T.",
    clientPhone: "+357 99 345 678",
    clientInitials: "CT",
    isNew: false,
    bookingId: "#BK-0038",
    date: "Fri, 15 May",
    time: "14:00",
    staff: "George",
    status: "No-show - cancelled",
    amount: "€120",
    paymentType: "Paid"
  },
  {
    clientName: "Eleni P.",
    clientPhone: "+357 96 789 012",
    clientInitials: "EP",
    isNew: true,
    bookingId: "#BK-0037",
    date: "Sat, 16 May",
    time: "16:30",
    staff: "Vivi",
    status: "No-show - waived",
    amount: "€30",
    paymentType: "Refunded"
  },
  {
    clientName: "John Doe",
    clientPhone: "+123 566 889",
    clientInitials: "JD",
    isNew: true,
    bookingId: "#BK-0036",
    date: "Saturday, May 9",
    time: "10:00 - 11:20 AM",
    staff: "George",
    status: "Cancelled by customer",
    amount: "€40",
    paymentType: "Refunded"
  },
  {
    clientName: "Nikos G.",
    clientPhone: "+357 96 789 666",
    clientInitials: "NG",
    isNew: true,
    bookingId: "#BK-0035",
    date: "Saturday, May 9",
    time: "10:00 - 11:20 AM",
    staff: "George",
    status: "Late cancellation",
    amount: "€40",
    paymentType: "Pay at venue"
  },
  {
    clientName: "Anna M.",
    clientPhone: "+357 96 234 111",
    clientInitials: "AM",
    isNew: false,
    bookingId: "#BK-0034",
    date: "Saturday, May 9",
    time: "10:00 - 11:20 AM",
    staff: "George",
    status: "Late cancellation",
    amount: "€40",
    paymentType: "Prepaid"
  },
  {
    clientName: "Rania M.",
    clientPhone: "+357 96 678 555",
    clientInitials: "RM",
    isNew: true,
    bookingId: "#BK-0033",
    date: "Saturday, May 9",
    time: "10:00 - 11:20 AM",
    staff: "George",
    status: "Late cancellation",
    amount: "€40",
    paymentType: "Paid"
  },
  {
    clientName: "John Doe",
    clientPhone: "+123 566 889",
    clientInitials: "JD",
    isNew: false,
    bookingId: "#BK-0032",
    date: "Saturday, May 9",
    time: "10:00 - 11:20 AM",
    staff: "George",
    status: "Cancelled by customer",
    amount: "€40",
    paymentType: "No refund"
  },
  {
    clientName: "John Doe",
    clientPhone: "+123 566 889",
    clientInitials: "JD",
    isNew: false,
    bookingId: "#BK-0031",
    date: "Saturday, May 9",
    time: "10:00 - 11:20 AM",
    staff: "George",
    status: "Canceled",
    amount: "€40",
    paymentType: "Pay at venue"
  },
  {
    clientName: "Demetra H.",
    clientPhone: "+357 99 345 678",
    clientInitials: "DH",
    isNew: false,
    bookingId: "#BK-0030",
    date: "Sat, 23 May",
    time: "14:30",
    staff: "Anna",
    status: "Canceled",
    amount: "€65",
    paymentType: "Prepaid"
  },
  {
    clientName: "Petros N.",
    clientPhone: "+357 99 345 678",
    clientInitials: "PN",
    isNew: true,
    bookingId: "#BK-0029",
    date: "Sun, 24 May",
    time: "16:00",
    staff: "George",
    status: "Pending",
    amount: "€55",
    paymentType: "Pay at venue"
  },
  {
    clientName: "Marina S.",
    clientPhone: "+357 99 890 123",
    clientInitials: "MS",
    isNew: false,
    bookingId: "#BK-0028",
    date: "Mon, 25 May",
    time: "10:30",
    staff: "Vivi",
    status: "Completed",
    amount: "€130",
    paymentType: "Pay at venue"
  },
  {
    clientName: "Michalis P.",
    clientPhone: "+357 99 890 123",
    clientInitials: "MP",
    isNew: true,
    bookingId: "#BK-0027",
    date: "Tue, 26 May",
    time: "12:30",
    staff: "Anna",
    status: "Cancelled by customer",
    amount: "€35",
    paymentType: "Refunded"
  },
  {
    clientName: "Katerina Z.",
    clientPhone: "+357 99 456 123",
    clientInitials: "KZ",
    isNew: false,
    bookingId: "#BK-0026",
    date: "Wed, 27 May",
    time: "15:30",
    staff: "George",
    status: "Upcoming",
    amount: "€105",
    paymentType: "Pay at venue"
  },
  {
    clientName: "Sophia L.",
    clientPhone: "+357 99 456 123",
    clientInitials: "SL",
    isNew: true,
    bookingId: "#BK-0025",
    date: "Thu, 28 May",
    time: "11:00",
    staff: "Vivi",
    status: "Upcoming",
    amount: "€80",
    paymentType: "Prepaid"
  },
  {
    clientName: "Pavlos G.",
    clientPhone: "+357 99 678 901",
    clientInitials: "PG",
    isNew: false,
    isManual: true,
    bookingId: "#BK-0024",
    date: "Fri, 29 May",
    time: "13:00",
    staff: "Anna",
    status: "Pending",
    amount: "€0",
    paymentType: "Fee waived"
  },
  {
    clientName: "Yiannis A.",
    clientPhone: "+357 99 678 901",
    clientInitials: "YA",
    isNew: true,
    bookingId: "#BK-0023",
    date: "Sat, 30 May",
    time: "17:00",
    staff: "George",
    status: "Completed",
    amount: "€115",
    paymentType: "Paid"
  },
  {
    clientName: "Lia V.",
    clientPhone: "+357 99 678 901",
    clientInitials: "LV",
    isNew: false,
    bookingId: "#BK-0022",
    date: "Sun, 31 May",
    time: "09:00",
    staff: "Vivi",
    status: "Cancelled by customer",
    amount: "€45",
    paymentType: "Refunded"
  },
  {
    clientName: "Stefanos M.",
    clientPhone: "+357 99 678 901",
    clientInitials: "SM",
    isNew: true,
    bookingId: "#BK-0021",
    date: "Mon, 1 Jun",
    time: "14:30",
    staff: "Anna",
    status: "Upcoming",
    amount: "€90",
    paymentType: "Pay at venue"
  },
  {
    clientName: "Niki C.",
    clientPhone: "+357 99 678 901",
    clientInitials: "NC",
    isNew: false,
    bookingId: "#BK-0020",
    date: "Tue, 2 Jun",
    time: "16:00",
    staff: "George",
    status: "Upcoming",
    amount: "€70",
    paymentType: "Prepaid"
  },
  {
    clientName: "Alexia F.",
    clientPhone: "+357 99 678 901",
    clientInitials: "AF",
    isNew: true,
    isManual: true,
    bookingId: "#BK-0019",
    date: "Wed, 3 Jun",
    time: "10:00",
    staff: "Vivi",
    status: "Pending",
    amount: "€50",
    paymentType: "Pay at venue"
  },
  {
    clientName: "Marios S.",
    clientPhone: "+357 99 678 901",
    clientInitials: "MS",
    isNew: false,
    bookingId: "#BK-0018",
    date: "Thu, 4 Jun",
    time: "12:00",
    staff: "Anna",
    status: "Completed",
    amount: "€125",
    paymentType: "Paid"
  },
  {
    clientName: "Elena V.",
    clientPhone: "+357 99 678 901",
    clientInitials: "EV",
    isNew: true,
    bookingId: "#BK-0017",
    date: "Fri, 5 Jun",
    time: "15:00",
    staff: "George",
    status: "Cancelled by customer",
    amount: "€30",
    paymentType: "Refunded"
  },
  {
    clientName: "Savvas N.",
    clientPhone: "+357 99 678 901",
    clientInitials: "SN",
    isNew: false,
    bookingId: "#BK-0016",
    date: "Sat, 6 Jun",
    time: "09:30",
    staff: "Vivi",
    status: "Upcoming",
    amount: "€80",
    paymentType: "Pay at venue"
  },
  {
    clientName: "Zoe G.",
    clientPhone: "+357 99 678 901",
    clientInitials: "ZG",
    isNew: true,
    bookingId: "#BK-0015",
    date: "Sun, 7 Jun",
    time: "11:30",
    staff: "Anna",
    status: "Upcoming",
    amount: "€60",
    paymentType: "Prepaid"
  },
  {
    clientName: "Lucas P.",
    clientPhone: "+357 99 678 901",
    clientInitials: "LP",
    isNew: false,
    bookingId: "#BK-0014",
    date: "Mon, 8 Jun",
    time: "13:00",
    staff: "George",
    status: "Pending",
    amount: "€45",
    paymentType: "Pay at venue"
  },
  {
    clientName: "Lydia K.",
    clientPhone: "+357 99 678 901",
    clientInitials: "LK",
    isNew: true,
    bookingId: "#BK-0013",
    date: "Tue, 9 Jun",
    time: "16:30",
    staff: "Vivi",
    status: "Completed",
    amount: "€100",
    paymentType: "Paid"
  },
  {
    clientName: "Rania M.",
    clientPhone: "+357 99 678 901",
    clientInitials: "RM",
    isNew: false,
    bookingId: "#BK-0012",
    date: "Wed, 10 Jun",
    time: "10:30",
    staff: "Anna",
    status: "Cancelled by customer",
    amount: "€40",
    paymentType: "Refunded"
  },
  {
    clientName: "Loucas A.",
    clientPhone: "+357 99 678 901",
    clientInitials: "LA",
    isNew: true,
    bookingId: "#BK-0011",
    date: "Thu, 11 Jun",
    time: "13:00",
    staff: "George",
    status: "Pending",
    amount: "€0",
    paymentType: "Fee waived"
  }
];

export const initialClientsData = [
  {
    name: "Sara L.",
    joined: "Since Jan 2024",
    phone: "+357 99 123 456",
    visitText: "11 May 2026",
    visitSub: "Last visit",
    isNext: false,
    visits: 18,
    spent: "€1,440",
    tag: "VIP",
    tagBg: "bg-[#FAEEDA]",
    tagColor: "text-[#633806]",
    avatarBg: "bg-[#E1F5EE]",
    avatarText: "SL"
  },
  {
    name: "Yiota M.",
    joined: "Since Nov 2023",
    phone: "+357 96 901 234",
    visitText: "Wed, 13 May · 10:00",
    visitSub: "Next booking",
    isNext: true,
    visits: 12,
    spent: "€960",
    tag: "Regular",
    tagBg: "bg-neutral-100",
    tagColor: "text-neutral-600",
    avatarBg: "bg-[#FAEEDA]",
    avatarText: "YM"
  },
  {
    name: "Maria K.",
    joined: "Since Feb 2024",
    phone: "+357 96 567 444",
    visitText: "Thu, 14 May · 11:30",
    visitSub: "Next booking",
    isNext: true,
    visits: 4,
    spent: "€320",
    tag: "VIP",
    tagBg: "bg-[#FAEEDA]",
    tagColor: "text-[#633806]",
    avatarBg: "bg-[#E6F1FB]",
    avatarText: "MK"
  },
  {
    name: "Christos T.",
    joined: "Since Sep 2023",
    phone: "+357 99 345 678",
    visitText: "Fri, 15 May · 14:00",
    visitSub: "Last visit",
    isNext: false,
    visits: 24,
    spent: "€2,160",
    tag: "VIP",
    tagBg: "bg-[#FAEEDA]",
    tagColor: "text-[#633806]",
    avatarBg: "bg-[#E1F5EE]",
    avatarText: "CT"
  },
  {
    name: "Eleni P.",
    joined: "Since Apr 2024",
    phone: "+357 96 789 012",
    visitText: "Sat, 16 May · 16:30",
    visitSub: "Last visit",
    isNext: false,
    visits: 3,
    spent: "€150",
    tag: "New",
    tagBg: "bg-[#E6F1FB]",
    tagColor: "text-[#0C447C]",
    avatarBg: "bg-[#FCE4E4]",
    avatarText: "EP"
  },
  {
    name: "Andreas S.",
    joined: "Since Dec 2023",
    phone: "+357 96 345 222",
    visitText: "Sun, 17 May · 10:00",
    visitSub: "Next booking",
    isNext: true,
    visits: 9,
    spent: "€720",
    tag: "Regular",
    tagBg: "bg-neutral-100",
    tagColor: "text-neutral-600",
    avatarBg: "bg-[#E6F1FB]",
    avatarText: "AS"
  },
  {
    name: "Nikos G.",
    joined: "Since May 2024",
    phone: "+357 96 789 666",
    visitText: "Mon, 18 May · 12:00",
    visitSub: "Next booking",
    isNext: true,
    visits: 2,
    spent: "€160",
    tag: "New",
    tagBg: "bg-[#E6F1FB]",
    tagColor: "text-[#0C447C]",
    avatarBg: "bg-[#EEEDFE]",
    avatarText: "NG"
  },
  {
    name: "Anna M.",
    joined: "Since Mar 2024",
    phone: "+357 96 234 111",
    visitText: "Tue, 19 May · 15:00",
    visitSub: "Last visit",
    isNext: false,
    visits: 7,
    spent: "€490",
    tag: "Regular",
    tagBg: "bg-neutral-100",
    tagColor: "text-neutral-600",
    avatarBg: "bg-[#FCE4E4]",
    avatarText: "AM"
  },
  {
    name: "Lydia K.",
    joined: "Since Jan 2024",
    phone: "+357 99 678 555",
    visitText: "10 Jun 2026",
    visitSub: "Last visit",
    isNext: false,
    visits: 14,
    spent: "€1,120",
    tag: "VIP",
    tagBg: "bg-[#FAEEDA]",
    tagColor: "text-[#633806]",
    avatarBg: "bg-[#EEEDFE]",
    avatarText: "LK"
  },
  {
    name: "Rania M.",
    joined: "Since Aug 2024",
    phone: "+357 96 678 555",
    visitText: "Fri, 15 May · 15:30",
    visitSub: "Next booking",
    isNext: true,
    visits: 6,
    spent: "€180",
    tag: "Regular",
    tagBg: "bg-neutral-100",
    tagColor: "text-neutral-600",
    avatarBg: "bg-[#EEEDFE]",
    avatarText: "RM"
  }
];

export const initialScheduleData = [
  {
    time: "09:00 PM",
    name: "Maria K.",
    service: "Hair colour - 60 min",
    payment: "$100",
    platformFee: "$20",
    remainingFee: "$80",
    staff: "Anna",
    lead: "New customer",
  },
  {
    time: "09:00 PM",
    name: "Maria K.",
    service: "Hair colour - 60 min",
    payment: "$100",
    platformFee: "0",
    remainingFee: "$100",
    staff: "George",
    lead: "Returning",
  },
  {
    time: "09:00 PM",
    name: "Maria K.",
    service: "Hair colour - 60 min",
    payment: "$100",
    platformFee: "0",
    remainingFee: "$100",
    staff: "George",
    lead: "Returning",
  },
  {
    time: "09:00 PM",
    name: "Maria K.",
    service: "Hair colour - 60 min",
    payment: "$100",
    platformFee: "$20",
    remainingFee: "$20",
    staff: "George",
    lead: "Returning",
  }
];

export const initialTimelineEvents = [
  { time: "10:30", name: "Maria K.", detail: "Lash Extensions - Elena", duration: "120 min - Return client" },
  { time: "14:00", name: "Sofia C.", detail: "Bridal Make-up - Elena", duration: "Strovolos - First booking" },
  { time: "16:30", name: "Anna N.", detail: "Manicure & Gel - Elena", duration: "Limassol - +€15 travel" }
];

export const initialActivityFeed = [
  {
    id: 1,
    type: "booking",
    text: "New client booked — Maria K. - Hair colour. Deposit €20 collected.",
    time: "2 min ago",
    icon: StarIcon,
    bg: "bg-[#E1F5EE]",
    color: "text-[#085041]"
  },
  {
    id: 2,
    type: "confirm",
    text: "Nikos P. confirmed for tomorrow at 10:30.",
    time: "1 hr ago",
    icon: CalendarCheckIcon,
    bg: "bg-blue-50",
    color: "text-blue-600"
  },
  {
    id: 3,
    type: "payout",
    text: "SEPA payout received — €210 for May no-show fees.",
    time: "Yesterday",
    icon: ReceiptTextIcon,
    bg: "bg-amber-50",
    color: "text-amber-600"
  },
  {
    id: 4,
    type: "cancel",
    text: "Elena S. cancelled. €18 deposit refunded automatically.",
    time: "2 days ago",
    icon: Cancel01Icon,
    bg: "bg-red-50",
    color: "text-red-600"
  }
];
