import { Recommendation } from "@/components/ServiceCard";

export const mockExploreServices: Recommendation[] = [
  {
    id: "1",
    title: "Soho Vintage Barbers | Sheikh Zayed Road",
    rating: 4.9,
    reviews: 299,
    categories: ["Barber", "Salon"],
    lastVisited: "Last visited 2 months ago",
    startingPrice: 12,
    image: "/img/service_demo.jpg",
    travelsToYou: true,
    travelLocations: ["Larnaca", "Limassol", "+4 more"],
    hasDiamond: true,
  },
  {
    id: "2",
    title: "Soho Vintage Barbers | Sheikh Zayed Road",
    rating: 4.9,
    reviews: 299,
    categories: ["Barber", "Salon"],
    location: "Sheikh Zayed Road, Dubai",
    distance: "3km away",
    lastVisited: "Last visited 2 months ago",
    startingPrice: 12,
    image: "/img/service_demo.jpg",
    noDeposit: true,
  },
  {
    id: "3",
    title: "Soho Vintage Barbers | Sheikh Zayed Road",
    rating: 4.9,
    reviews: 299,
    categories: ["Barber", "Salon"],
    lastVisited: "Last visited 2 months ago",
    startingPrice: 12,
    image: "/img/service_demo.jpg",
    travelsToYou: true,
    travelLocations: ["Larnaca", "Limassol", "+4 more"],
    noDeposit: true,
  },
  {
    id: "4",
    title: "Soho Vintage Barbers | Sheikh Zayed Road",
    rating: 4.9,
    reviews: 299,
    categories: ["Barber", "Salon"],
    location: "Sheikh Zayed Road, Dubai",
    distance: "3km away",
    lastVisited: "Last visited 2 months ago",
    startingPrice: 12,
    image: "/img/service_demo.jpg",
  },
  {
    id: "5",
    title: "Precision Men's Grooming | Larnaca",
    rating: 4.6,
    reviews: 92,
    categories: ["Barber"],
    lastVisited: "Last visited 2 weeks ago",
    startingPrice: 18,
    image: "/img/service_demo.jpg",
    travelsToYou: true,
    travelLocations: ["Larnaca", "Nicosia"],
  },
  {
    id: "6",
    title: "Serenity Yoga Studio | Limassol",
    rating: 5.0,
    reviews: 74,
    categories: ["Wellness"],
    lastVisited: "Last visited 3 days ago",
    startingPrice: 30,
    image: "/img/service_demo.jpg",
    noDeposit: true,
  }
];
